# Generated by Django 2.0.6 on 2018-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=255, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=255, verbose_name='first Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last Name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='phone Number')),
                ('born_date', models.DateField(verbose_name='born Date')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, verbose_name='sex')),
                ('minsa_code', models.CharField(max_length=20, verbose_name='MINSA Code')),
            ],
            options={
                'verbose_name': 'Staff member',
                'verbose_name_plural': 'Staff members',
            },
        ),
    ]
